--Inserting data to the users table

INSERT INTO USERS (Username, Pass, Ranking)
VALUES ('kurosaki', 'zangestu', 'Rep'),
('orihime', 'fairy', 'Student'),
('asta', 'wizard', 'Rep'),
('noelle', 'water', 'Student'),
('naruto', 'dattebayo', 'Student'),
('hinata', 'byakuagan', 'Student'),
('sasuke', 'sharigan', 'Student'),
('seven', 'scissor', 'Student'),
('whis', 'angel', 'Rep'),
('beerus', 'hakai', 'Student'),
('goku', 'saiyan', 'Student'),
('izuku', 'oneforall', 'Student'),
('Val', 'vpude0', 'Student'),
 ('Morly', 'mclemitt1', 'Student'),
 ('Rustie', 'rneillans2', 'Rep'),
 ('Emmerich', 'echasteney3', 'Student'),
 ('Eolande', 'eduthy4', 'Rep'),
 ('Adolphus', 'agorini5', 'Student'),
 ('Selene', 'sodeegan6', 'Student'),
 ('Chrysler', 'cgehringer7', 'Staff'),
 ('Becka', 'bcrigin8', 'Staff'),
 ('Florette', 'fremnant9', 'Staff'),
 ('Constantino', 'cparamora', 'Student'),
 ('Cchaddie', 'clavalb', 'Staff'),
 ('Virgina', 'vbywatersc', 'Staff'),
 ('Phyllys', 'praulstond', 'Staff'),
 ('Alisa', 'aheighwaye', 'Staff'),
 ('Gris', 'gvigusf', 'Rep'),
 ('Hagen', 'hbryettg', 'Rep'),
 ('Monty', 'mclynterh', 'Rep'),
 ('Lida', 'ltalloni', 'Rep'),
 ('Basia', 'bphetheanj', 'Student'),
 ('Bald', 'bstockowk', 'Staff'),
 ('Sebastien', 'sjelfsl', 'Rep'),
 ('Angel', 'akindellm', 'Staff'),
 ('Kandace', 'kvanderwaltn', 'Student'),
 ('Caressa', 'cpawelkeo', 'Student'),
 ('Selia', 'sgerkensp', 'Rep'),
 ('Goldy', 'gboyseq', 'Student'),
 ('Shell', 'scamachor', 'Student'),
 ('Benjamin', 'bpitrollos', 'Staff'),
 ('Dania', 'dbeattiet', 'Student')
